### ISSUE TITLE
`import moment from 'moment';` does not work

### ISSUE THREAD

**Issue by brandynbennett** [stefanpenner/ember-moment#292] opened 2018-10-23 21:50 UTC
When I use `import moment from 'moment';` as the README specifies I get an error that the module can't be found. Is this because `ember-cli-moment-shim` is a `devDependency` instead of a `dependency`?? Using version 7.7.0 of this addon

**Comment by aaronlelevier** [comment] 2018-11-05 22:58
I installed the package earlier today, and was able to use the `import moment from 'moment';` inside of a component fine.

**Comment by jasonmit** [comment] 2019-04-18 05:49
Unable to reproduce, closing.  If you put together a reproduction of the issue please create a new issue.

**Closed by jasonmit** 2019-04-18 05:49 UTC
