### ISSUE TITLE
Failed to install in a new ember app

### ISSUE THREAD

**Issue by netoho** [stefanpenner/ember-moment#72] opened 2015-07-30 00:26 UTC
Hi, I'm having the next problem.
Executing 'ember init' and immediately after 'ember install ember-moment' gives
```
version: 1.13.5
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Installed packages for tooling via npm.
installing ember-moment
  install addon ember-cli-moment-shim
Installed packages for tooling via npm.
Cannot read property 'reduce' of undefined
TypeError: Cannot read property 'reduce' of undefined
    at Class.module.exports.Task.extend.installBlueprint (/home/neto/Development/new/node_modules/ember-cli/lib/tasks/addon-install.js:54:24)
    at Class.<anonymous> (/home/neto/Development/new/node_modules/ember-cli/lib/tasks/addon-install.js:43:19)
    at lib$rsvp$$internal$$tryCatch (/home/neto/Development/new/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/neto/Development/new/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/home/neto/Development/new/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/home/neto/Development/new/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at process._tickCallback (node.js:355:11)
```
I'm using using ember-cli 1.13.5

**Comment by jasonmit** [comment] 2015-07-30 01:27
Ping @stefanpenner known issue?  I haven't seen this before.  Otherwise, I'll dig into it tonight.

**Comment by stefanpenner** [comment] 2015-07-30 01:28
> Ping @stefanpenner known issue?

i believe this is the first time i've seen this one.

**Comment by jasonmit** [comment] 2015-07-30 01:50
Confirmed it works on 1.13.1 and breaks on 1.13.5 and looks like it may be related to https://github.com/ember-cli/ember-cli/pull/4406

I'll dig deeper after dinner to see at which end this needs to be patched

**Comment by jasonmit** [comment] 2015-07-30 02:51
Okay, dug deeper https://github.com/ember-cli/ember-cli/blob/v1.13.5/lib/models/blueprint.js#L1043 should `taskOptions['package'] = options;` should be `taskOptions['packages'] = options;`

@stefanpenner I'll work around this and go through addAddonsToProject (plural) instead and version a temp fix.

**Comment by jasonmit** [comment] 2015-07-30 07:55
@netoho until my patch is merged and ember-cli publishes with my change then you'll need to continue to use ember-cli-1.13.1.

**Comment by stefanpenner** [comment] 2015-07-30 15:26
will cut another cli after breakfast, thanks @jasonmit for the patch.

**Comment by jasonmit** [comment] 2015-07-30 16:36
:+1:

**Comment by aceofspades** [comment] 2015-07-30 18:13
+1

**Comment by stefanpenner** [comment] 2015-07-30 18:18
+1

**Comment by jasonmit** [comment] 2015-07-30 20:44
Thanks @stefanpenner.  Closing now that ember-cli 1.13.6 addresses this.

**Closed by jasonmit** 2015-07-30 20:44 UTC

**Comment by stefanpenner** [comment] 2015-07-30 20:50
:)
