### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by codepreneur** [stefanpenner/ember-moment#48] opened 2015-05-19 12:36 UTC
when `ember install ember-moment` I get:

```
version: 0.2.5
Installed packages for tooling via npm.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/johndoe/frontend/node_modules/ember-cli/lib/models/project.js:475:53
    at baseFindIndex (/Users/johndoe/frontend/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)
    at /Users/johndoe/frontend/node_modules/ember-cli/node_modules/lodash/internal/createFind.js:18:19
    at Project.findAddonByName (/Users/johndoe/frontend/node_modules/ember-cli/lib/models/project.js:474:20)
    at Class.module.exports.Task.extend.findDefaultBlueprintName (/Users/johndoe/frontend/node_modules/ember-cli/lib/tasks/addon-install.js:63:30)
    at Class.module.exports.Task.extend.installBlueprint (/Users/johndoe/frontend/node_modules/ember-cli/lib/tasks/addon-install.js:52:30)
    at Class.<anonymous> (/Users/johndoe/frontend/node_modules/ember-cli/lib/tasks/addon-install.js:42:19)
    at lib$rsvp$$internal$$tryCatch (/Users/johndoe/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/johndoe/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/johndoe/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)

```

and `ember -v` gives me:

```
version: 0.2.5
node: 0.12.2
npm: 2.10.0
```

**Comment by stefanpenner** [comment] 2015-05-19 22:01
hmm strange, seems to work for me.

```
± % ember install ember-moment                                                                                                  !12208
version: 0.2.5
Installed packages for tooling via npm.
installing
Installing browser packages via Bower...
  cached git://github.com/jasonmit/ember-cli-moment-shim.git#0.1.0
  cached git://github.com/moment/moment.git#2.10.3
Installed browser packages via Bower.
Installed addon package.
```

**Comment by stefanpenner** [comment] 2015-05-19 22:02
can you share more information?

**Comment by codepreneur** [comment] 2015-05-19 23:05
The addon works and it saves dev into `package.json`, it just throws this error when installing for the first time.

```
npm version
{ 'frontend': '0.0.0',
  npm: '2.10.0',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.2',
  openssl: '1.0.1m',
  uv: '1.4.2-node1',
  v8: '3.28.73',
  zlib: '1.2.8' }
```

and..

```
DEBUG: -------------------------------
DEBUG: Ember                  : 1.12.0
DEBUG: Ember Data          : 1.0.0-beta.17
DEBUG: jQuery                   : 1.11.3
DEBUG: Model Fragments  : 0.3.2
DEBUG: -------------------------------
```

**Comment by stefanpenner** [comment] 2015-05-19 23:20
> DEBUG: -------------------------------
> DEBUG: Ember                  : 1.12.0
> DEBUG: Ember Data          : 1.0.0-beta.17
> DEBUG: jQuery                   : 1.11.3
> DEBUG: Model Fragments  : 0.3.2
> DEBUG: -------------------------------

this is the client-side versions, not really very useful. Can you share the ember cli version?

**Comment by stefanpenner** [comment] 2015-05-19 23:21
also, my attempt was on a freshly generated ember-cli app. So the first time appeared to be ok?

**Comment by Kilowhisky** [comment] 2015-05-20 15:47
I am also getting the error during initial install

ember -v
version: 0.2.5
node: 0.12.0
npm: 2.10.0

**Comment by sethphillips** [comment] 2015-05-20 20:21
Also having this issue
version: 0.2.5
node: 0.12.0
npm: 2.10.0


Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/sethphillips/Sites/carousel/ui/node_modules/ember-cli/lib/models/project.js:475:53
    at baseFindIndex (/Users/sethphillips/Sites/carousel/ui/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)
    at /Users/sethphillips/Sites/carousel/ui/node_modules/ember-cli/node_modules/lodash/internal/createFind.js:18:19
    at Project.findAddonByName (/Users/sethphillips/Sites/carousel/ui/node_modules/ember-cli/lib/models/project.js:474:20)
    at Class.module.exports.Task.extend.findDefaultBlueprintName (/Users/sethphillips/Sites/carousel/ui/node_modules/ember-cli/lib/tasks/addon-install.js:63:30)
    at Class.module.exports.Task.extend.installBlueprint (/Users/sethphillips/Sites/carousel/ui/node_modules/ember-cli/lib/tasks/addon-install.js:52:30)
    at Class.<anonymous> (/Users/sethphillips/Sites/carousel/ui/node_modules/ember-cli/lib/tasks/addon-install.js:42:19)
    at lib$rsvp$$internal$$tryCatch (/Users/sethphillips/Sites/carousel/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/sethphillips/Sites/carousel/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/sethphillips/Sites/carousel/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)


both moment.js and ember-cli-moment-shim/moment-shim.js were not added to bower.json

**Comment by sethphillips** [comment] 2015-05-20 20:38
to be clear, the addon works, it just does not pull in the bower items automagically

**Comment by Kilowhisky** [comment] 2015-05-20 21:49
I just got this same error with another unrelated ember addon 'ember-moment' so maybe this is an ember-cli issue?

**Comment by stefanpenner** [comment] 2015-05-20 22:12
> so maybe this is an ember-cli issue?

maybe some race condition? Unfortuantely, without a reproduction case this is tricky to track down...

**Comment by Kilowhisky** [comment] 2015-05-22 20:55
Looks like here is the bug and a fix for it! 

https://github.com/ember-cli/ember-cli/issues/4102

**Comment by ksnyde** [comment] 2015-06-07 10:00
I think that https://github.com/ember-cli/ember-cli/issues/4102 solves the WARN message about no repository but does not address the underlying issue being discussed here (aka, `ember install` giving the *Cannot read property 'name' of undefined*). I just got this same error installing `ember-cli-mirage` and I have @cibernox's 1.0.0 release of `ember-disable-proxy-controllers` (which does remove the npm WARN message).

    cli: 0.2.7
    node: 0.12.4
    npm: 2.11.0

**Comment by chiragmongia** [comment] 2015-06-11 11:03
I am facing the same issue with `ember-cli 0.2.7`

`ember -v --versose` returns the following-
version: 0.2.7
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
npm: 2.11.0

**Comment by stefanpenner** [comment] 2015-06-11 14:00
> Btw, I tried installing ember-cli-pretender and ember-cli-mirage

and did those work?

**Comment by chiragmongia** [comment] 2015-06-12 07:27
Nope. Those didn't work!

**Comment by ksnyde** [comment] 2015-06-12 11:53
I *was* able to install all the bower dependencies manually and mirage is now working as intended.

**Comment by jasonmit** [comment] 2015-06-27 00:32
Closed as this is an upstream issue in ember-cli

**Closed** 2015-06-27 00:31 UTC
