### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by medokin** [stefanpenner/ember-moment#14] opened 2014-11-13 15:50 UTC
Is there an easy way to change the language?

**Comment by felipeleusin** [comment] 2015-01-28 01:52
Hi,
Do you guys need help with this? Began using ember-moment but now need to add support for localization and got kinda stuck... https://github.com/edgycircle/ember-pikaday suggests using the brocfile and a initializer which sounds good for a global setting (my use case). Maybe something along this lines?

**Comment by jasonmit** [comment] 2015-01-28 02:41
I am days away from releasing `ember-intl` which has relative time and date support using the native `Intl` API.  Moment is not a dependency either.  It will likely be released tomorrow or Thursday as the latest.

**Comment by jasonmit** [comment] 2015-01-29 05:28
https://github.com/yahoo/ember-intl the helper you are looking for is like format time date and relative

—

**Comment by stefanpenner** [comment] 2015-01-29 06:16
@jasonmit nice!

**Comment by larryisthere** [comment] 2015-01-31 12:53
This feature is needed strongly. I'd prefer a global configuration.

**Comment by jasonmit** [comment] 2015-02-01 07:58
> I'd prefer a global configuration

 `moment.locale('fr');`  // Set the default/global locale

**Comment by jelhan** [comment] 2015-04-09 15:10
I'm using [ember-cli-i18n](https://github.com/dockyard/ember-cli-i18n) which stores current locale as `locale` property of application. I use an initializer to set locale for `moment` on init and register an observer for locale changes which updates moment locale. I'm currently not using `ember-moment` but a helper to format dates with moment. But this solution doesn't update already formatted dates. I'm also using [ember-cli-bootstrap-datepicker](ember-cli-bootstrap-datepicker) which uses a bindable locale option.

Since there isn't a common way to store locale setting in application yet I would prefer using a bindable locale option in `ember-moment`. If you decide to support a global locale option following `ember-cli-i18n` and use `locale` property of application would probably the best way to go.

**Comment by jelhan** [comment] 2015-04-09 15:44
I was able to update my little moment helper to observe locale changes and rerender view. Perhaps it's a starting point. I'm not sure if rerender helper view is the right way to go.

```
import Ember from "ember";
/* global moment */

export default function(date, options) {
  var format = options.hash.format ? options.hash.format : 'LLLL',
      application = this.get('container').lookup('application:main'),
      self = this;
  
  Ember.addObserver(application, 'locale', self, self.rerender);
  
  return moment(date).format( format );
}
```

**Comment by jasonmit** [comment] 2015-04-10 20:53
@jelhan usually the locale does not change throughout the lifetime of app.  Are you sure you need to observe `locale` versus forcing an app reload in the event the user does change their locale.

I say this because I'm in the process of ripping this functionality out of `ember-intl` and would like to hear your use case.

**Comment by jelhan** [comment] 2015-04-11 11:51
@jasonmit I have to support on-the-fly switching of locales without a reload of page in my app and therefore moved from [ember-i18n](https://github.com/jamesarosen/ember-i18n) to [ember-cli-i18n](https://github.com/dockyard/ember-cli-i18n). Of course it depends on your project if on-the-fly update of locales is needed or if observing locales should be avoided due to performance issues.

**Comment by jasonmit** [comment] 2015-04-11 19:28
> I have to support on-the-fly switching of locales without a reload of page in my app

I should have been more clear when, you get this behavior if you force an app reset on locale change.

```
var app = this.container.lookup('application:main');
app.reset();
```

**Comment by seven7seven** [comment] 2015-07-31 11:30
Changing locales doesn't seem to work for me right now. I added a default locale, as specified in the README, but moment's locale seems to be set in tone to 'en'. Any luck with this?

**Comment by jelhan** [comment] 2015-07-31 11:57
@jasonmit `app.reset();` does reset `model` and therefore does not meet all my requirements. Had discussed the issue without real solution sometime ago on [stackoverflow](http://stackoverflow.com/questions/26091303/recommended-way-to-rerender-page-in-ember-after-language-switch). ember-i18n observes locale changes since 4.0.0 which was released two month ago. At least since that change other addons dealing with locales should also observe locale changes.

@seven7seven Do you [include the locale](https://github.com/stefanpenner/ember-moment#i18n-support) you specified as default locale? Also have a check if your default locale is [supported by moment.js](https://github.com/moment/moment/tree/2.10.3/locale).

**Comment by jasonmit** [comment] 2015-07-31 15:35
@seven7seven are you able to reproduce this and show me so I can look into it.

@jelhan 

> At least since that change other addons dealing with locales should also observe locale changes.

I'd be happy to review a pull request but I don't feel this functionality is a popular use-case.  And as I said, ember-intl does support the functionality you are after and supports date,time and relative time formatting.

**Comment by jasonmit** [comment] 2015-08-07 01:15
https://github.com/stefanpenner/ember-moment/pull/75 will allow for inlining locales, global is supported and documented

**Comment by jasonmit** [comment] 2015-08-07 19:38
Closing as there is now documentation on setting global and local locales

**Closed by jasonmit** 2015-08-07 19:38 UTC
Labels: enhancement
